# Generated by Django 5.2.14 on 2026-05-20 11:40

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Datum')),
                ('teaser', models.TextField(blank=True, verbose_name='Kurzbeschreibung')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('embed', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Überschrift'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Text'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Bild'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {'icon': 'openquote', 'label': 'Zitat'}), 4: ('wagtail.blocks.URLBlock', (), {'icon': 'media', 'label': 'Embed/Link'})}, verbose_name='Inhalt')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Titelbild')),
            ],
            options={
                'verbose_name': 'Allgemeiner Blogbeitrag',
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SectionIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('basecontentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.basecontentpage')),
            ],
            options={
                'verbose_name': 'Allgemeiner Blogbeitrag',
            },
            bases=('content.basecontentpage',),
        ),
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('basecontentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.basecontentpage')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Autor/in')),
                ('genre', models.CharField(blank=True, default='Fantasy', max_length=255, verbose_name='Genre')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bewertung 1–10')),
            ],
            options={
                'verbose_name': 'Bücher',
            },
            bases=('content.basecontentpage',),
        ),
        migrations.CreateModel(
            name='GamePage',
            fields=[
                ('basecontentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.basecontentpage')),
                ('platform', models.CharField(default='PC / Steam', max_length=255, verbose_name='Plattform')),
                ('steam_url', models.URLField(blank=True, verbose_name='Steam-Link')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bewertung 1–10')),
            ],
            options={
                'verbose_name': 'Spiele',
            },
            bases=('content.basecontentpage',),
        ),
        migrations.CreateModel(
            name='MiscPage',
            fields=[
                ('basecontentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.basecontentpage')),
            ],
            options={
                'verbose_name': 'Sonstiges',
            },
            bases=('content.basecontentpage',),
        ),
        migrations.CreateModel(
            name='MovieSeriesPage',
            fields=[
                ('basecontentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.basecontentpage')),
                ('provider', models.CharField(blank=True, max_length=255, verbose_name='Streaminganbieter/Kino')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bewertung 1–10')),
            ],
            options={
                'verbose_name': 'Filme & Serien',
            },
            bases=('content.basecontentpage',),
        ),
        migrations.CreateModel(
            name='RecipePage',
            fields=[
                ('basecontentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.basecontentpage')),
                ('servings', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Portionen')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Dauer')),
                ('thermomix', models.BooleanField(default=True, verbose_name='Thermomix-Rezept')),
                ('ingredients', wagtail.fields.RichTextField(blank=True, verbose_name='Zutaten')),
            ],
            options={
                'verbose_name': 'Kochen',
            },
            bases=('content.basecontentpage',),
        ),
        migrations.CreateModel(
            name='TravelPage',
            fields=[
                ('basecontentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.basecontentpage')),
                ('destination', models.CharField(blank=True, max_length=255, verbose_name='Reiseziel')),
                ('travel_date', models.CharField(blank=True, max_length=255, verbose_name='Reisezeitraum')),
            ],
            options={
                'verbose_name': 'Reisen',
            },
            bases=('content.basecontentpage',),
        ),
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='content.basecontentpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='basecontentpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='content.ContentTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
