# Generated by Django 5.2.14 on 2026-05-20 12:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecontentpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('gallery', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 Spalten'), ('3', '3 Spalten')], 'label': 'Spalten'}), 4: ('wagtail.blocks.ListBlock', (2,), {'label': 'Bilder'}), 5: ('wagtail.blocks.StructBlock', [[('columns', 3), ('images', 4)]], {'label': 'Bildergalerie', 'template': 'content/blocks/gallery.html'})}),
        ),
    ]
