# Generated by Django 5.2.14 on 2026-05-20 15:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_basecontentpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecontentpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('embed', 3), ('gallery', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Überschrift'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Text'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Einzelbild'}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': 'YouTube / Video'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 Spalten'), ('3', '3 Spalten')], 'label': 'Spalten'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Bilder'}), 7: ('wagtail.blocks.StructBlock', [[('columns', 4), ('images', 6)]], {'icon': 'image', 'label': 'Bildergalerie', 'template': 'content/blocks/gallery.html'})}),
        ),
    ]
