# Generated by Django 5.2.14 on 2026-05-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_basecontentpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieseriespage',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], null=True, verbose_name='Bewertung'),
        ),
    ]
