# Generated by Django 5.2.14 on 2026-05-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_movieseriespage_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieseriespage',
            name='provider',
            field=models.CharField(blank=True, choices=[('netflix', 'Netflix'), ('amazon-prime-video', 'amazon Prime Video'), ('amazon-buy-video', 'amazon Kauf Video'), ('disney-plus', 'Disney+'), ('apple-tv-plus', 'Apple TV+'), ('wow', 'WOW'), ('paramount-plus', 'Paramount+'), ('kino', 'Kino'), ('mediathek', 'Mediathek'), ('blu-ray-dvd', 'Blu-ray / DVD'), ('sonstiges', 'Sonstiges')], max_length=50, verbose_name='Streaminganbieter/Kino'),
        ),
    ]
