# Generated by Django 5.2.14 on 2026-05-20 21:30

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_movieseriespage_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecontentpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('sized_image', 5), ('embed', 6), ('gallery', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Überschrift'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Text'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Einzelbild'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Bild'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Volle Breite'), ('medium', '2/3 Breite'), ('small', '1/3 Breite zentriert')], 'label': 'Darstellung'}), 5: ('wagtail.blocks.StructBlock', [[('image', 3), ('size', 4)]], {'icon': 'image', 'label': 'Einzelbild mit Größe'}), 6: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': 'YouTube / Video'}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 Spalten'), ('3', '3 Spalten')], 'label': 'Spalten'}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Bilder'}), 10: ('wagtail.blocks.StructBlock', [[('columns', 7), ('images', 9)]], {'icon': 'image', 'label': 'Bildergalerie', 'template': 'content/blocks/gallery.html'})}),
        ),
        migrations.AlterField(
            model_name='movieseriespage',
            name='provider',
            field=models.CharField(blank=True, choices=[('netflix', 'Netflix'), ('amazon-prime-video', 'Amazon Prime Video'), ('disney-plus', 'Disney+'), ('apple-tv-plus', 'Apple TV+'), ('wow', 'WOW'), ('paramount-plus', 'Paramount+'), ('kino', 'Kino'), ('mediathek', 'Mediathek'), ('blu-ray-dvd', 'Blu-ray / DVD'), ('sonstiges', 'Sonstiges')], max_length=50, verbose_name='Streaminganbieter/Kino'),
        ),
    ]
