# Generated by Django 5.2.14 on 2026-05-20 21:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_basecontentpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecontentpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 4), ('embed', 5), ('gallery', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Überschrift'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Text'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Bild'}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Volle Breite'), ('medium', '2/3 Breite'), ('small', '1/3 Breite zentriert')], 'label': 'Darstellung'}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('size', 3)]], {'icon': 'image', 'label': 'Einzelbild'}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': 'YouTube / Video'}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 Spalten'), ('3', '3 Spalten')], 'label': 'Spalten'}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Bilder'}), 9: ('wagtail.blocks.StructBlock', [[('columns', 6), ('images', 8)]], {'icon': 'image', 'label': 'Bildergalerie', 'template': 'content/blocks/gallery.html'})}),
        ),
    ]
